### ISSUE TITLE
Mapping between CSV data and meaningful property names?

### ISSUE THREAD

**Issue by GavinRay97** [EldenRingDatabase/erdb#1]
Hiya -- thanks for compiling this!

I'm curious if there is a definition/key to what the properties mean?
For instance, in the Weapons data, the properties seem to have obscure names:

```json
    {
        "Row ID": "1100",
        "Row Name": "",
        "disableParam_NT": "1",
        "behaviorVariationId": "0",
        "sortId": "9999999",
        "wanderingEquipId": "0",
        "weight": "1",
        "weaponWeightRate": "0",
        "fixPrice": "0",
        "reinforcePrice": "0",
        "sellValue": "-1",
        "correctStrength": "30",
        "correctAgility": "60",
        "correctMagic": "0",
        "correctFaith": "0",
        "physGuardCutRate": "0",
        "magGuardCutRate": "0",
        "fireGuardCutRate": "0",
        "thunGuardCutRate": "0",
        "spEffectBehaviorId0": "-1",
        "spEffectBehaviorId1": "-1",
        "spEffectBehaviorId2": "-1",
        // etc
    },
```

**Comment by Phil25** [comment]
Hey!

So part of the project is to actually map this data into something readable. What you posted is the raw data extracted from the game that is used as source only.

But it's still a WIP with plenty left. For now, only [talismans](https://github.com/EldenRingDatabase/erdb/blob/master/talismans.json), [spirit ashes](https://github.com/EldenRingDatabase/erdb/blob/master/spirit-ashes.json) and [armor](https://github.com/EldenRingDatabase/erdb/blob/master/armor.json) are done. Weapons, ashes of war and others are on the way but it might take some time to figure out the layout and complete the parsers.

If you wanna browse the raw data, you can check out [Yapped Rune Bear](https://github.com/vawser/Yapped-Rune-Bear). It has meaningful explanations for these properties that are understandable for the most part, like [EquipParamWeapon](https://github.com/vawser/Yapped-Rune-Bear/blob/main/Paramdex/ER/Defs/EquipParamWeapon.xml).

**Comment by GavinRay97** [comment]
Apparently you cannot reply to GH issue threads via email. That's what I get for trying once.

Response from 3 days ago I tried to send (whoops!):

> Ohhh got it -- thank you! Didn't know about this Yapped Rune Bear and it having meaningful explanations, absolutely will check this out

**Comment by Phil25** [comment]
That's a note for me as well then!

Glad you like YRB. Perhaps you can return here after a while, see how this database gets rid of the obscure datamining once it releases. 🙂

**Comment by GavinRay97** [comment]
Ohhh got it -- thank you! Didn't know about this Yapped Rune Bear and it
having meaningful explanations, absolutely will check this out
