### ISSUE TITLE
Any plans for new version? [1.12 + DLC]

### ISSUE THREAD

**Issue by shinonome-shizuka** [EldenRingDatabase/erdb#12]
I need erdb to parse data from game to full fill my wiki project, and FS has changed some DCX formats so no one can reach game data right now.

**Comment by sovietspaceship** [comment]
This will be worked on, at the moment we only have a very adhoc set of changes to make it work that are very hacky and won't work in general.

If you need updated data please DM me on discord `@sovietspaceship` for the time being. I recommend using https://github.com/vawser/Smithbox to extract raw params for the time being, and UXM has been updated for the DLC.

**Comment by shinonome-shizuka** [comment]
> This will be worked on, at the moment we only have a very adhoc set of changes to make it work that are very hacky and won't work in general.
> 
> If you need updated data please DM me on discord `@sovietspaceship` for the time being. I recommend using https://github.com/vawser/Smithbox to extract raw params for the time being, and UXM has been updated for the DLC.

Thanks for replying. I have extracted some raw params with SmithBox, that's useful.
I will keep star on your project, it's amazing.
