### ISSUE TITLE
Armor missing

### ISSUE THREAD

**Issue by CyberGiant7** [EldenRingDatabase/erdb#2]
Hey, thank you for you work.
I'm using the json database and I just noticed that the Godskin Noble armor has been swapped with that of the Godskin Apostle, while the Godskin Apostle armor is missing

**Comment by Phil25** [comment]
Hey good catch, thanks.

I took a break from erdb but when I get back to it around next week I'll check it out. Speaking of which, I'm glad that you're using it but do mind that it's still WIP and things will change.

Thanks for the report.

**Comment by Phil25** [comment]
Fixed in https://github.com/EldenRingDatabase/erdb/commit/9cc9a4601a1e2ccc528c06e7aa1a04d030c5267e

Also corrected the data for 1.07 _only_. Previous versions will have the wrong armor for the time being until generators are more complete and I'll downpatch the game to update them.

**Comment by Phil25** [comment]
All versions are now updated.
